### ISSUE TITLE
I can not run your file

### ISSUE THREAD

**Issue by Akanikko** [DavidTorresOcana/Adaptive_and_Fault_Tolerant_Flight_Control_Systems#1]
I have matlab version2019a, and I can not run your code can you please help?

**Comment by DavidTorresOcana** [comment]
Hello

From what I understand on your personal message, there is a problem with newer version of Matlab.
This repo was compiled and run with Matlab 2015a without problems.

I changed the lines causing troubles but I was unable to verify it runs in Matlab 2019.
Please inform if any problems occurs.

Regards
