### ISSUE TITLE
Thesis PDF link is lost

### ISSUE THREAD

**Issue by PilotWang** [DavidTorresOcana/Adaptive_and_Fault_Tolerant_Flight_Control_Systems#2]
Thesis PDF link is lost, could you please provide a PDF file of your thesis?

**Comment by DavidTorresOcana** [comment]
Hello
Thank you for pointing it out. I just updated the link
You would have to request a copy of the Thesis to Cranfield library, I am afraid.

**Comment by PilotWang** [comment]
Thank you for your prompt response.

**Comment by PilotWang** [comment]
Thank you for your prompt response.
